L6
VladFiliucov/blogster pull request #6
Opened 2017-06-21 22:51 UTC by VladFiliucov

Cannot read property 'route' of undefined.

2017-06-28 05:24 UTC, index01d requested changes

2017-06-28 05:24 UTC, index01d commented on src/components/ui/BlogPage.jsx
> +import { postsPath } from 'helpers/routes/posts.js'
без js

2017-06-28 05:24 UTC, index01d commented on src/components/ui/BlogPage.jsx
> +        { this.props.error && <h1>Something wrong with {this.props.error}</h1> }
нужно выделять компонент с описанием ошибки

2017-06-28 05:24 UTC, index01d commented on src/components/ui/BlogPage.jsx
> +              <SearchBar searchPosts={ this.searchPosts } {...this.props} />
не похоже, чтобы здесь был this.searchPosts

2017-06-28 05:24 UTC, index01d commented on src/components/ui/BlogPage.jsx
> +export default class BlogPage extends Component {
определение компонента как stateful выглядит избыточным

2017-06-28 05:24 UTC, index01d commented on src/components/ui/BlogItem.jsx
>        <Like
Полагаю если бы здесь использовался `<LikeContainer />`, а не `<Like />`, то контейнер бы подхватывался и работал, к тому же не пришлось бы передавать кучу свойств, хватило бы postId

2017-06-28 05:24 UTC, index01d commented on src/components/ui/BlogItem.jsx
> +const BlogItem = ({ post, posts}) => (
про все записи компоненту с одной записью знать явно не следует

2017-06-28 11:20 UTC, VladFiliucov commented on src/components/ui/BlogItem.jsx
>        <Like
А коннект в свою очередь сам отрендерит приконекченный компонент! Гениально. BlogPage изначально был в контейнерах по этому ничего не пришлось менять.

2017-06-28 11:23 UTC, VladFiliucov commented on src/components/ui/BlogItem.jsx
> +const BlogItem = ({ post, posts}) => (
Но у меня редьюсер инкремента принимает посты из акшена и постId. Все посты не доходят по иерархии до LikeContainer'a, так-что в own propsя их не ожидаю увидеть. Я могу тогда обратиться в редьюсере к стору всего приложения?

2017-06-28 11:24 UTC, VladFiliucov commented on src/components/ui/BlogPage.jsx
> +              <SearchBar searchPosts={ this.searchPosts } {...this.props} />
Кстати, это тоже нужно будет делать как-то через редакс?

2017-06-28 17:54 UTC, index01d commented on src/components/ui/BlogPage.jsx
> +              <SearchBar searchPosts={ this.searchPosts } {...this.props} />
я пока вообще не понял это что, его в объекте нет совсем

2017-06-28 17:55 UTC, index01d commented on src/components/ui/BlogItem.jsx
> +const BlogItem = ({ post, posts}) => (
так stateToProps и можно ухватить из общего единого состояния приложения вроде бы.

2017-06-28 17:55 UTC, index01d commented on src/components/ui/BlogItem.jsx
> +const BlogItem = ({ post, posts}) => (
а инкремент может обработать например reducer постов

2017-06-28 17:56 UTC, index01d commented on src/components/ui/BlogItem.jsx
> +const BlogItem = ({ post, posts}) => (
или можно для лайков иметь отдельное состояние (с приятным бонусом в виде расширения количества сущностей, которым можно ставить лайк)

тут уж на вкус и цвет, можно и так и так

2017-06-30 18:43 UTC, index01d requested changes

2017-06-30 18:43 UTC, index01d commented on src/components/ui/BlogItem.jsx
> +    <Link  to={{pathname: '/posts', search: `postId=${post.id}`}} >
здесь желательно использовать функцию-pathHelper, иначе сложно будет переименовывать роуты в дальнейшем

2017-06-30 18:43 UTC, index01d commented on src/components/ui/BlogItem.jsx
>          likes={post.details.likes}
это свойство теперь явно лишнее

2017-06-30 18:43 UTC, index01d commented on src/components/ui/Like.jsx
> +          onClick={() => this.props.likePost(this.props.posts)}
контейнерная логика оказалась в презентационном компоненте, если использовать mergeProps (3-й параметр функции connect, получает в качестве аргумента stateProps, dispatchProps), то можно обойтись без передачи списка постов сюда

2017-06-30 18:43 UTC, index01d commented on src/components/ui/SearchBar.jsx
> +    const history = createHistory();
коллбэк должен прийти из контейнера, зачем презентационному компоненту знать про какое-то там createHistory?

2017-06-30 18:43 UTC, index01d commented on src/components/ui/SearchBar.jsx
> +    const history = createHistory();
к тому же лучше эту часть обернуть как модуль helpers/history и импортировать уже готовый history-singleton

2017-06-30 18:43 UTC, index01d commented on src/components/ui/SearchBar.jsx
> +    this.props.fetchPosts(this.state.searchTerm);
почему бы не сделать это в prepareData у роута? зачем это здесь?

2017-06-30 18:43 UTC, index01d commented on src/components/ui/SearchBar.jsx
>      this.setState({ searchTerm: '' });
выглядит лишним

2017-06-30 18:43 UTC, index01d commented on src/routes/BlogList.js
> +    store.dispatch(fetchPosts())
параметры для поиска нужно выхватить и подставить из URL в этой функции, а не где либо еще

2017-06-30 18:54 UTC, VladFiliucov commented on src/components/ui/SearchBar.jsx
>      this.setState({ searchTerm: '' });
Так почистить форму? У меня же controlled input

2017-06-30 19:44 UTC, index01d commented on src/components/ui/SearchBar.jsx
>      this.setState({ searchTerm: '' });
ну во-первых выше происходит переход с обнулением состояния по сути, во-вторых почему бы не оставить там значение текущего поиска?

2017-06-30 19:48 UTC, VladFiliucov commented on src/components/ui/BlogItem.jsx
>          likes={post.details.likes}
но у меня тут нет в состоянии приложения поста в данный момент. В диспатч ту пропс все посты. Тут нужно mergeProps использовать?

2017-06-30 19:52 UTC, VladFiliucov commented on src/components/ui/SearchBar.jsx
> +    this.props.fetchPosts(this.state.searchTerm);
Так тут же handleSubmit. То есть вы имеете в виду, добавить в строку браузера, а там уже обработать в роутере колбэк... А это лучше?

2017-06-30 19:53 UTC, VladFiliucov commented on src/components/ui/SearchBar.jsx
> +    this.props.fetchPosts(this.state.searchTerm);
Разве так не читабильнее? По-моему сразу видно, что происходит при сабмите

2017-06-30 20:31 UTC, index01d commented on src/components/ui/SearchBar.jsx
> +    this.props.fetchPosts(this.state.searchTerm);
В презентационном компоненте не должно быть низкоуровневой реализации того, что происходит при сабмите. Не выполняется условие единственности ответственности презентационного компонента

2017-06-30 20:32 UTC, index01d commented on src/components/ui/BlogItem.jsx
>          likes={post.details.likes}
mergeProps нужно использовать в контейнере, не здесь.

2017-06-30 20:32 UTC, index01d commented on src/components/ui/SearchBar.jsx
> +    this.props.fetchPosts(this.state.searchTerm);
Так тут же handleSubmit. То есть вы имеете в виду, добавить в строку браузера, а там уже обработать в роутере колбэк... А это лучше?

> так точно, т.к. можно будет прийти по прямой ссылке и получить результат.

2017-06-30 22:10 UTC, VladFiliucov commented on src/components/ui/SearchBar.jsx
> +    const history = createHistory();
history тут вообще не нужен. Можно использовать push из реакт-рутер-редакса. Он работает сам по себе

2017-06-30 22:12 UTC, VladFiliucov commented on src/components/ui/SearchBar.jsx
> +    const history = createHistory();
Хотя вру) в урл ничего не приходит

2017-07-02 06:03 UTC, index01d approved these changes
Оставил два важных замечания. Но даю пропуск на 7й

2017-07-02 06:03 UTC, index01d commented on src/actions/Posts.js
> +      .then(() => {
все ж таки это должно быть в контейнере. Не ясно зачем это здесь. actionCreator по определению должен быть функцией, принимающей аргументы и возвращающей описание-дескриптор действия. Побочные эффекты связанные с логикой приложения здесь лишние (как убедимся в 7-ом уроке).

2017-07-02 06:03 UTC, index01d commented on src/components/ui/BlogItem.jsx
> +    <Link  to={postUrlObject(post.id)} >
по хорошему здесь должен быть уже готовый url, подоткнуть его к post стоило бы в контейнере, тогда презентационный компонент будет не в курсе роутерной логики и не будет иметь от нее зависимости.

2017-07-11 20:36 UTC, VladFiliucov commented on src/components/ui/BlogItem.jsx
> +    <Link  to={postUrlObject(post.id)} >
Этот компонент рендерится в индексном компоненте. Он приконекчен в сврю очередь к контейнеру со списком. Как оттуда передать айди определенного поста я не знаю. Или подразумевается сделать еще один шоу контейнер?

2017-07-11 21:14 UTC, VladFiliucov commented on src/actions/Posts.js
> +      .then(() => {
В смысле пушить в хистори в контейнере? Вот SearchContainer. Так?

import { connect } from 'react-redux';
import { fetchPosts } from 'actions/Posts';
import history from 'routes/history';

import SearchBar from 'components/ui/SearchBar';

function mapDispatchToProps(dispatch) {
  return {
    fetchPosts: (searchTerm) => {
      dispatch(fetchPosts(searchTerm));
      history.push({pathname: '/', search: searchTerm});
    }
  };
}

export default connect(null, mapDispatchToProps)(SearchBar);

2017-07-12 06:28 UTC, index01d commented on src/actions/Posts.js
> +      .then(() => {
зачем здесь делать dispatch? почему его не сделать в prepareData?

2017-07-12 06:28 UTC, index01d commented on src/components/ui/BlogItem.jsx
> +    <Link  to={postUrlObject(post.id)} >
можно сделать map по списку

2017-07-12 06:29 UTC, index01d commented on src/components/ui/BlogItem.jsx
> +    <Link  to={postUrlObject(post.id)} >
и сгенерировать url для каждого

2017-07-12 07:55 UTC, VladFiliucov commented on src/components/ui/BlogItem.jsx
> +    <Link  to={postUrlObject(post.id)} >
Я понимаю, как сделать этот мап, из презентационного компонента со списком. Но, как это сделать из mapDispatchToProps - ума не приложу
```
const mapStateToProps = (state) => ({
  posts: state.posts.posts,
  isLoading: state.posts.isLoading,
  error: state.posts.error
});
```
Заменить ключ posts на копию ключа posts с добавленной в каждый объект ключ со ссылкой?
Сделать отдельный массив объектов links, в ктором будет id поста и вычисленная ссылка? Но тогда ведь мне нужно будет делать еще один find по этому массиву, что-б закинуть правильную ссылку в презентационный компонент. Сомнительный выигрыш.

2017-07-12 14:17 UTC, index01d commented on src/components/ui/BlogItem.jsx
> +    <Link  to={postUrlObject(post.id)} >
> Заменить ключ posts на копию ключа posts с добавленной в каждый объект ключ со ссылкой?

правильно

2017-07-14 06:39 UTC, VladFiliucov commented on src/components/ui/BlogItem.jsx
> +    <Link  to={postUrlObject(post.id)} >
Так?
```
import update from 'immutability-helper';

import { postUrlObject } from 'helpers/routes/post';

const mapStateToProps = (state) => ({
  posts: state.posts.posts
    .map(post => update(post,
      {
        $merge: {
          postUrl: postUrlObject(post.id)
        }
      }
    )),
  isLoading: state.posts.isLoading,
  error: state.posts.error
});

    <Link  to={post.postUrl} >

```

2017-07-18 07:28 UTC, index01d commented on src/components/ui/BlogItem.jsx
> +    <Link  to={postUrlObject(post.id)} >
update использовать здесь не обязательно, можно просто `assign({}, post, { url: '...' })`

2017-07-18 07:28 UTC, index01d commented on src/components/ui/BlogItem.jsx
> +    <Link  to={postUrlObject(post.id)} >
лаконичнее будет

2017-07-20 13:01 UTC, merged